service:
  type: NodePort
  port: 51820
  nodePort: 31820
  protocol: UDP

persistence:
  enabled: true
  storageClassName: local-path
  size: 1Gi

wireguard:
  serverAddress: "10.34.0.1/24"
  serverCidr: "10.34.0.0/24"
  clients:
    - friendlyName: "window-pc"
      allowedIPs: "10.34.0.2/32"
      publicKey: "eG/nTxeO0AY/ktJvGWTa8i4WW8S3R/BLOL2/2wEnqlA="

replicaCount: 1
