service:
  type: NodePort
  port: 51820
  nodePort: 31820
  protocol: UDP

persistence:
  enabled: true
  storageClassName: "local-path"
  size: 1Gi

wireguard:
  clients:
    - friendlyName: "window-pc"
      allowedIPs: "10.34.0.2/32"
      publicKey: "TjP7nEcANrLoH/KlWiT+zn3/KjTXk4M6gPQxXotpgSU="
