apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-server-ingress
  namespace: minecraft
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: mine.gistory.me.kr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minecraft-server
                port:
                  number: 25565
  tls:
    - secretName: mine-gistory-me-kr