apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: minecraft-tcp-route
  namespace: minecraft
spec:
  entryPoints:
    - minecraft
  routes:
    - match: HostSNI(`mine.gistory.me.kr`)
      services:
        - name: minecraft-server
          port: 25565
  tls:
    secretName: mine-gistory-me-kr