resources:
  requests:
    memory: 512Mi
    cpu: 500m

minecraftServer:
  eula: "TRUE"
  type: "VANILLA"
  difficulty: hard
  version: "LATEST"
  whitelist: "tkjftkjf"
  ops: "tkjftkjf"
  servicePort: 25565